name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Project
        run: |
          flutter create my_app --org=com.himalyan --project-name=himalyan_hydrogreens
          cp lib/main.dart my_app/lib/main.dart
          cd my_app
          flutter build apk --release --no-tree-shake-icons
          cp build/app/outputs/flutter-apk/app-release.apk ../app-release.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: himalyan-hydrogreens-app
          path: app-release.apk
